### ISSUE TITLE
Logo requests

### ISSUE THREAD

**Issue by edh72** [jsdelivr/fontfamous.github.io#37]
Boston Globe
http://www.followuppal.com/images/boston_globe.jpg

Market Watch (Dow Jones)
http://www.followuppal.com/images/MarketWatch_logo.png

The Street
http://www.followuppal.com/images/the_street_com.jpg

Information Week
http://www.followuppal.com/images/informationweek.png

SiliconValley.com
http://www.followuppal.com/images/siliconvalley.com.jpg

Yahoo Finance
http://www.followuppal.com/images/yahoo_finance_logo.png

**Comment by fontfamous** [comment]
Hey edh72, thanks for your suggestions!

Could you submit these _each_ as a **separate** logo request as per the protocol in contributing.md? 

This helps us keep things streamlined, and others submitting requests can see what has already been submitted. 

Thank you, these are all great suggestions.
- Anthony
