### ISSUE TITLE
DIY Logos

### ISSUE THREAD

**Issue by edh72** [jsdelivr/fontfamous.github.io#38]
Would you consider allowing user submitted logos?

There are several local news outlets I'd like logos for that are probably not large enough for you guys to waste time on.  

But I'd gladly pay a photoshop(?) expert to convert them for me and submit them.

**Comment by fontfamous** [comment]
Edh72, this is a good question. Let me discuss with the team and I'll get back to you. 

Anthony

**Comment by edh72** [comment]
Thanks, Anthony.
