### ISSUE TITLE
Add more logos

### ISSUE THREAD

**Issue by samerbuna** [jsdelivr/fontfamous.github.io#4]
https://www.business.com
http://www.cio.com
http://www.shrm.org
http://www.socialmediatoday.com
https://www.socialmediaexplorer.com
http://socialmediaclub.org
http://socialmedia.biz
http://www.geektime.com

**Comment by fontfamous** [comment]
Please break these down into individual requests following the protocol in CONTRIBUTING.md

**Comment by gaglage** [comment]
http://www.motogp.com
