### ISSUE TITLE
Logo Request: Black Enterprise

### ISSUE THREAD

**Issue by ckeeney** [jsdelivr/fontfamous.github.io#44]
http://www.blackenterprise.com/

I looked, but they do not appear to have any brand guide.

[Here is the official logo file used on their homepage](http://www.blackenterprise.com/wp-content/themes/blackenterprise/images/masthead-logos/be-home-logo.png).

[Here is the most hi-res version of their logo I could find, though it is not hosted on their servers and may not be official](http://www.blackenterprise.com/wp-content/themes/blackenterprise/images/masthead-logos/be-home-logo.png).   It is missing the "Wealth for Life" tagline

I attached both logos in case the URL changes.

![](http://www.blackenterprise.com/wp-content/themes/blackenterprise/images/masthead-logos/be-home-logo.png)

![](http://socialmediaweek.org/lagos/files/2016/01/Untitled-5-11.png)

**Comment by ckeeney** [comment]
The contribution guide says to add a "Logo Request" label, but I don't believe I have permissions to modify labels of issues, and I did not see an option to add a label when I was creating the issue.

**Comment by MartinKolarik** [comment]
@Drgy I think this one is still missing?
