### ISSUE TITLE
Re-organize the repo and fix bugs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/fontfamous.github.io#50]
- Must work with jsDelivr
- A new design will come soon
- Organize files
- Other?

**Comment by MartinKolarik** [comment]
Published as https://www.jsdelivr.com/package/npm/fontfamous and updated the website: https://jsdelivr.github.io/FontFamous/

**Comment by jimaek** [comment]
Domain is live https://fontfamous.com/
Designer will start working next weeks
