### ISSUE TITLE
Automate addition of new logos

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/fontfamous.github.io#51]
Can we use Clearbit https://clearbit.com/logo to automate things?

**Comment by fontfamous** [comment]
Not sure exactly if this will work as desired.

It tends to do a  Square icon?  Maybe it would work for some logos.

**Comment by fontfamous** [comment]
this is the freelancer on fiverr that did this work before

https://www.fiverr.com/elinaprimaka

**Comment by fontfamous** [comment]
she did 8 logos for $25 which I thought was a great deal.
