### ISSUE TITLE
FontFamous v2

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/fontfamous.github.io#53]
Stuff to do:
- New design https://github.com/jsdelivr/FontFamous/issues/54
- New readme
- More logos
- Other?

**Comment by jdorfman** [comment]
Promote:
- [ ] HN
- [ ] ProductHunt
- [ ] tips@techcrunch.com
- [ ] tips@mashable.com

**Comment by jimaek** [comment]
@jdorfman wanna help with promotion of v2? We are basically done
