### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/fontfamous.github.io#54]
- Better design
- Including SRI https://github.com/jsdelivr/FontFamous/issues/52

**Comment by jimaek** [comment]
![fontfamous](https://user-images.githubusercontent.com/1834071/46586067-5e7e7700-ca79-11e8-877b-a0e7bc32de8a.png)
@MartinKolarik @jdorfman @fontfamous Here is the first version. What do you all think?

**Comment by jdorfman** [comment]
Love it. I think TechCrunch might actually pick this up.

**Comment by jimaek** [comment]
Design was uploaded to Avocode for coding and assets are attached here
[refontfamousredesign.zip](https://github.com/jsdelivr/FontFamous/files/3031341/refontfamousredesign.zip)

**Comment by drgy** [comment]
@jimaek can you please ask the designer about the cursor?

**Comment by jimaek** [comment]
What cursor?

**Comment by drgy** [comment]
Sorry i think i understood the design wrong, there is what appears to be a custom cursor when hovering over links/buttons, what im not sure about is if its system default or really custom?

**Comment by fontfamous** [comment]
I found the original zip files from the designer with the icons.

Also, I had these done on Fiverr from user *elinaprimaka *at a very
reasonable price.

The platform I used to create the font files was http://fontastic.me/

**Comment by drgy** [comment]
@fontfamous can you please send the original zip file?
