### ISSUE TITLE
v2 launch

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/fontfamous.github.io#56]
@jdorfman You are the expert on dev tools. What are we missing to start promoting it? 
@fontfamous What do you think about v2.0?

Maybe we should add some more logos?
Once everything is perfect I will submit 2.0 to ProductHunt and later HN. Any other ideas except from that?

**Comment by jdorfman** [comment]
Lgtm start promotion =)

**Comment by jimaek** [comment]
Goes live tomorrow https://www.producthunt.com/posts/font-famous-2-0 01:00AM Pacific Time
Get ready to upvote

**Comment by jimaek** [comment]
Its live
