### ISSUE TITLE
Logo Request: CNET’s Download

### ISSUE THREAD

**Issue by heidihelen** [jsdelivr/fontfamous.github.io#60]
Could you add CNET’s Download logo?

Download blog ([download.cnet.com](https://download.cnet.com/))

**Comment by jimaek** [comment]
I think we should only have cnet https://github.com/jsdelivr/FontFamous/issues/61
no need to separate per section

**Comment by heidihelen** [comment]
I suggest Download because they did an article on my app and have a different logo than CNET.

**Comment by jimaek** [comment]
Yeah but nobody will recognize it, its a generic download icon

**Comment by heidihelen** [comment]
It's not just a generic download icon, it also has a typeface with it. You can see it on the website for my app, [Capsicum](https://capsicum.app).

**Comment by jimaek** [comment]
It looks like any other download button. 
The idea of the font is to add logos of reputable press publications like new york times. CNET too to a lesser extend, but their download sub-category doesn't match the idea.

**Comment by heidihelen** [comment]
Here is the full logo here. As you can see, it’s not just a generic icon, it also has wording with it. It is your call, though.

![Download Logo](https://capsicum.app/images/Featured/download.com-logo.svg)

**Comment by jimaek** [comment]
Exactly, the wording makes it even more a generic download button. Sorry but I think it goes against the point of the project

**Comment by heidihelen** [comment]
Okay… I suppose it could get confused with a download button. But my point was it's not just a generic icon - it comes with a wordmark (wording/typeface) with it. And yes, they are a subdivision of CNET so I suppose if I get featured by them again, I could just use CNET’s logo, but I do like using one with the precise publication.
