### ISSUE TITLE
Logo Request: MacStories

### ISSUE THREAD

**Issue by heidihelen** [jsdelivr/fontfamous.github.io#63]
Could you add the logo for MacStories?

MacStories ([macstories.net](https://www.macstories.net))

**Comment by jimaek** [comment]
I don't think they are reputable enough to get added

**Comment by heidihelen** [comment]
I disagree. They write lots of tech articles and reviews on apps. So many developers who have their apps featured would want to share press links for them. They are very well known in my industry.
