### ISSUE TITLE
Logo Request: TWiT

### ISSUE THREAD

**Issue by heidihelen** [jsdelivr/fontfamous.github.io#64]
Could you add the logo for TWiT (This Week in Tech)?

TWiT ([twit.tv](https://twit.tv))

**Comment by jimaek** [comment]
I don't think they are reputable enough to get added

**Comment by heidihelen** [comment]
They have a lot of sponsors on their show so that suggests they have a wide audience, although I don't know the specific number. They promoted my app on an episode and seem to be pretty well known in the tech industry. You can read more about them [here](https://twit.tv/about/what-is-twit-tv). I list them as a press feature on the website for my app [Capsicum](https://capsicum.app) and I would like to see them added to a service like yours, so I could replace the individual logos with a font.
