### ISSUE TITLE
Logo Request: App Store

### ISSUE THREAD

**Issue by heidihelen** [jsdelivr/fontfamous.github.io#66]
Could you add the logo for Apple? Sometimes when you work on an app you get promoted on the App Store and sometimes it has a sharable link too.

**Comment by jimaek** [comment]
App store has its own logo, we should probably use that instead

**Comment by heidihelen** [comment]
They do have an app icon for the App Store, I am not sure if it is available as a vector. Usually, we say, “We had our app promoted by Apple on the App Store.”
